# Generated by Django 3.0.7 on 2020-06-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup', '0016_auto_20200606_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickup',
            name='rcNo',
        ),
    ]
