# Generated by Django 3.0.7 on 2020-06-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup', '0018_pickup_customer_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickup',
            old_name='user',
            new_name='pick_User',
        ),
        migrations.AddField(
            model_name='pickup',
            name='pick_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
