# Generated by Django 3.0.7 on 2020-06-13 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_address', models.TextField(blank=True, max_length=255, null=True)),
                ('phNo', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('rcNo', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(blank=True, choices=[('ASSIGNED', 'ASSIGNED'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='COMPLETED', max_length=255, null=True)),
                ('OdoMeter', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('FuelLevel', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=('1', '1'), max_length=7, null=True)),
                ('CDPlayer', models.BooleanField(default=False)),
                ('CigeretteCharger', models.BooleanField(default=False)),
                ('ToolKit', models.BooleanField(default=False)),
                ('ServiceBook', models.BooleanField(default=False)),
                ('Clock', models.BooleanField(default=False)),
                ('CarPerfume', models.BooleanField(default=False)),
                ('Jack', models.BooleanField(default=False)),
                ('SpareWheel', models.BooleanField(default=False)),
                ('Mats', models.BooleanField(default=False)),
                ('DickyMat', models.BooleanField(default=False)),
                ('BodyCover', models.BooleanField(default=False)),
                ('Antenna', models.BooleanField(default=False)),
                ('Remote', models.BooleanField(default=False)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('customerRemarks', models.TextField(null=True)),
                ('pick_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_remarks', models.TextField(blank=True, null=True)),
                ('customer_token', models.CharField(blank=True, max_length=255, null=True)),
                ('drop_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('drop_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drop_User', to=settings.AUTH_USER_MODEL)),
                ('pickup_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickup_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
