# Generated by Django 3.0.7 on 2020-06-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Completed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='drop_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='pick_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
