# Generated by Django 3.0.7 on 2020-06-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drop', '0002_drop_customer_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drop',
            old_name='user',
            new_name='drop_user',
        ),
        migrations.AlterField(
            model_name='drop',
            name='drop_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
