# Generated by Django 3.0.7 on 2020-06-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drop', '0003_auto_20200613_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drop',
            old_name='drop_user',
            new_name='user',
        ),
    ]
